### ISSUE TITLE
report generation problem

### ISSUE THREAD

**Issue by dduff617** [bschollnick/Indigo-survey#1]
I'm getting this error when trying to run survey plugin.   The error seems to occur after all the tests are done and the report is being generated.

Here's what I see in the logs:

   Survey Plugin                   Total Successes - 431
   Survey Plugin                   Total Failures - 13
   Survey Plugin                   Done processing devices
   Survey Plugin Error             Error in plugin execution MenuAction:

Traceback (most recent call last):
  File "plugin.py", line 341, in survey_3pass_manualUpdate
  File "plugin.py", line 311, in make_individual_reports
  File "plugin.py", line 184, in make_report
  File "/Library/Application Support/Perceptive Automation/Indigo 7.2/Plugins/survey2.indigoPlugin/Contents/Server Plugin/Cheetah/Template.py", line 1005, in __str__
  File "cheetah_DynamicallyCompiledCheetahTemplate_1545718435_73_64659.py", line 136, in respond
TypeError: hex() argument can't be converted to hex

**Comment by bschollnick** [comment]
I'll try to take a look into this in the next day or so.

As a work around, you can load the HTML file manually into safari or firefox, and view the report.

**Comment by bschollnick** [comment]
Fixed in v2.22 which I just released.  

I'm having an issue with it not being seen by the Indigo Plugin Store, so, you'll want to manually download the release for now.  

I'll leave this open, until I can get it recognized by the indigo plugin store.

**Comment by bschollnick** [comment]
Fixed.  I had to recreate the release to get it to post correctly.
